### ISSUE TITLE
Complilation error occured in rt_ai_network_model.c for ART-Pi project when using X-CUBE-AI7 7.0.0

### ISSUE THREAD

**Issue by KafCoppelia** [RT-Thread/RT-AK-plugin-stm32#13]
用`X-CUBE-AI 7.0.0`，在RT-AK中使用
```
python aitools.py --project="..\..\..\my_rtt_project" --model=".\Models\keras_mnist.h5" --platform=stm32 --log="..\..\..\my_rtt_project\Logs\log.log" --ext_tools="..\..\..\stm32ai-windows-7.0.0\windows" --cube_ai=".\platforms\plugin_stm32\X-CUBE-AI.7.0.0" --clear
```
可以成功生成代码，但在RTT Studio中，ART-Pi项目工程工具链`GNU Tools 6.3.1`，`GNU ARM Cross C Compiler`无论是gnu11/C11、gnu99/C99编译均出现以下报错（截取部分）：
![image](https://user-images.githubusercontent.com/69038090/170696685-e4d9b67a-8332-46df-9d76-f91dc942e72f.png)
![image](https://user-images.githubusercontent.com/69038090/170696565-adc49fd2-925c-4336-9ce4-b82b5d6917ef.png)
后面大多的错误都是由于程序开头这部分的报错导致。
初步分析了一下，是不是结构体通过宏定义还有嵌套的初始化，导致其内部元素都是动态生成，但是这个结构体程序并未事先声明其存储大小，因此报错。

**Comment by QiwenLi0729** [comment]
请查看以下rtconfig.h文件中是否有`#define RT_AI_USE_CUBE` 宏定义。如果没有，请加上这个宏. 建议每次在工程配置完成再进行模型生成，否则这个宏会被Studio配置给刷新掉。

**Comment by KafCoppelia** [comment]
加上以后，编译没问题了，但是链接出现问题：
![image](https://user-images.githubusercontent.com/69038090/171549829-69ec8628-27ab-4d1b-bf51-ad4eb8f6ff5c.png)
清一色的`uses VFP register arguments, rtthread.elf does not`，是需要修改CFLAGS？

**Comment by pinxue** [comment]
说明这些 .o 编译生成时的 -mfloat-abi 与 elf 的不同，clean 掉重编译，如果还有估计就得重新运行一下部署命令了。

**Comment by KafCoppelia** [comment]
THX，新建模板工程后按教程部署并编译成功。
> 请查看以下rtconfig.h文件中是否有#define RT_AI_USE_CUBE 宏定义。如果没有，请加上这个宏. 建议每次在工程配置完成再进行模型生成，否则这个宏会被Studio配置给刷新掉。

倒是每次更新软件包就会刷掉这个宏定义，挺麻烦的
